[workspace]
resolver = "2"
members = [
  "contracts/*",
]

[workspace.dependencies]
soroban-sdk = { version = "27.0.2", features = ["experimental_spec_shaking_v2"] }
stellar-access = { path = "../../openzeppelin/stellar-contracts/packages/access", version = "0.7.1" }
stellar-governance = { path = "../../openzeppelin/stellar-contracts/packages/governance", version = "0.7.1" }
stellar-macros = { path = "../../openzeppelin/stellar-contracts/packages/macros", version = "0.7.1" }
stellar-tokens = { path = "../../openzeppelin/stellar-contracts/packages/tokens", version = "0.7.1" }

[profile.release]
opt-level = "z"
overflow-checks = true
debug = 0
strip = "symbols"
debug-assertions = false
panic = "abort"
codegen-units = 1
lto = true

# For more information about this profile see https://soroban.stellar.org/docs/basic-tutorials/logging#cargotoml-profile
[profile.release-with-logs]
inherits = "release"
debug-assertions = true
